##################################
#
# Makefile para T-GTK codigo de C
#
ROOT = ../
include $(ROOT)config/global.mk
include $(ROOT)$(SETENV)


TARGET=libtgtk-misc.a
#SOURCES = misc.prg

PRGFLAGS=-I../include

SOURCE_TYPE=c
TGTK_INSTALL=../lib

include $(TGTK_DIR)/Rules.make
