# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../../

TARGET = test
SOURCES = pdf_demo.prg
LIBS=-L$(ROOT)lib -lpdf

include $(ROOT)Rules.make
