# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola
ROOT = ../../
TARGET = test
SOURCES = ejemplo4.prg

include $(ROOT)Rules.make

