/*  $Id: libgdaext.ch,v 1.2 2011/01/05 17:44:00 riztan Exp $ */
/*
 * Llamadas externas para ejecutar desde script.
 * (c)2008 Riztan Gutierrez
 */

 /* gnomedb */
 EXTERNAL GNOME_DB_INIT
 EXTERNAL GDA_CONFIG_SAVE_DATA_SOURCE
 EXTERNAL GNOME_DB_LOGIN_DIALOG_NEW
 EXTERNAL GNOME_DB_LOGIN_DIALOG_RUN
 EXTERNAL GDA_CLIENT_NEW
 EXTERNAL GNOME_DB_LOGIN_DIALOG_GET_DSN
 EXTERNAL GNOME_DB_LOGIN_DIALOG_GET_USERNAME
 EXTERNAL GNOME_DB_LOGIN_DIALOG_GET_PASSWORD
 EXTERNAL GDA_CLIENT_OPEN_CONNECTION
 EXTERNAL GDA_COMMAND_NEW
 EXTERNAL GDA_CONNECTION_EXECUTE_SELECT_COMMAND
 EXTERNAL GNOME_DB_GRID_NEW
 EXTERNAL GDA_CONNECTION_CLOSE
 EXTERNAL GDA_CONFIG_GET_PROVIDER_LIST

