/*  $Id: tgtkext.ch,v 1.2 2008/12/18 01:33:00 riztan Exp $ */
/*
 * Llamadas externas para ejecutar desde script.
 * (c)2008 Riztan Gutierrez
 */

 EXTERNAL MSG_INFO
 EXTERNAL MSGBOX
 EXTERNAL MSG_NOYES
 EXTERNAL MSG_OKCANCEL
// EXTERNAL MSG_ALERT

// GTK Functions
 EXTERNAL GTK_WINDOW_SET_ICON
 EXTERNAL GTK_WINDOW_SET_ICON_NAME
 EXTERNAL GTK_WINDOW_SET_ICON_FROM_FILE

/*
 EXTERNAL MSGABOUT
 EXTERNAL MSGBEEP
 EXTERNAL MSGGET
 EXTERNAL MSGLOGO
 EXTERNAL MSGMETER
 EXTERNAL MSGRUN
*/

 EXTERNAL GCALENDAR
 EXTERNAL GCOMBOBOX
 EXTERNAL GCOMBOBOX_CLIP
 EXTERNAL GMENU
 EXTERNAL GMENUITEM
 EXTERNAL GMENUSEPARATOR
 EXTERNAL GSTATUSBAR
 EXTERNAL GIMAGE
 EXTERNAL GICONVIEW
 EXTERNAL GMENUBAR
 EXTERNAL GMENUTEAROFF
 EXTERNAL GMENUITEMCHECK
 EXTERNAL GMENUITEMIMAGE
 EXTERNAL GTOOLTIP
 EXTERNAL GTOGGLEBUTTON
 EXTERNAL GRADIOBUTTON
 EXTERNAL GENTRY
 EXTERNAL GSPINBUTTON
 EXTERNAL GCHECKBOX
 EXTERNAL GTREEVIEWCOLUMN
 EXTERNAL GTEXTVIEW
 EXTERNAL GSOURCEVIEW
 EXTERNAL GTOOLBAR
 EXTERNAL GTOOLBUTTON
 EXTERNAL GBUTTON
 EXTERNAL GLIST
 EXTERNAL GFRAME
 EXTERNAL GALIGNMENT
 EXTERNAL GSEPARATOR
 EXTERNAL GPROGRESSBAR
 EXTERNAL GDRAWINGAREA
 EXTERNAL GTABLE

 /* native */
 EXTERNAL GTK_CONTAINER
 EXTERNAL GTK_WIDGET_SHOW_ALL


