##################################
#
# Makefile para libreria tp_ de Contrib en T-Gtk
#

TARGET=libtelepathy.a
SOURCES = telepath.prg

PRGFLAGS=-I../include

TGTK_INSTALL=../lib

CSOURCES=linux.c
include ../Rules.make

