##################################
#
# Makefile para libreria ATL , para ActiveX for Windows.
# 
#

TARGET=libax.a
SOURCES = axprg.prg

PRGFLAGS=-I../../include
TGTK_INSTALL=../../lib

CFLAGS= -DNONAMELESSUNION
CSOURCES=axev.c 
CPPSOURCES=axCpp.cpp

include ../../Rules.make
