ROOT = ../../../

TARGET = clientpop3
SOURCES = clientpop3.prg

#PRGFLAGS=-I$(ROOT)include
#LIBS=-L$(ROOT)src/gclass -lgclass -L$(ROOT)hbgtk -lhbgtk $(shell pkg-config --libs libglade-2.0) $(shell pkg-config --libs gtk+-2.0 ) -mwindows

# Libreria de servicios de Inet de xHarbour
#LIBS += -lhbtip

include $(ROOT)Rules.make
