TARGET = clientpop3
SOURCES = clientpop3.prg

#PRGFLAGS=-I../../../include
#LIBS=-L../../../src/gclass -lgclass -L../../../hbgtk -lhbgtk $(shell pkg-config --libs libglade-2.0) $(shell pkg-config --libs gtk+-2.0 ) -mwindows

# Libreria de servicios de Inet de xHarbour
LIBS += -ltip

include ../../../Rules.make
