# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

TARGET = ejemplo
SOURCES  = ejemplo.prg

include ../../../Rules.make

