##################################
#
# Makefile para T-GTK codigo de C
#

TARGET=libhbgtk.a
#CFLAGS+=-I. -I../include $(shell pkg-config --cflags gtk+-2.0)$(shell pkg-config --cflags libglade-2.0) -D__OLDHARBOUR__
CFLAGS+=-I. -I../include $(shell pkg-config --cflags gtk+-2.0)$(shell pkg-config --cflags libglade-2.0)

SOURCE_TYPE=c
TGTK_INSTALL=../lib

include ../Rules.make

