# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../../

TARGET = test
SOURCES = treestore.prg
#LIBS= -mwindows
#PRGFLAGS=-p
include $(ROOT)Rules.make

