# ONLY FOR GNU/Linux

ROOT = ../../../

TARGET = testprinter
SOURCES = testprinter.prg

#PRGFLAGS=-I$(ROOT)include
#LIBS=-L$(ROOT)src/gclass -lgclass -L$(ROOT)hbgtk -lhbgtk $(shell pkg-config --libs libglade-2.0) $(shell pkg-config --libs gtk+-2.0 )

include $(ROOT)Rules.make

