# ONLY FOR GNU/Linux
TARGET = testprinter
SOURCES = testprinter.prg

#PRGFLAGS=-I../../../include
#LIBS=-L../../../src/gclass -lgclass -L../../../hbgtk -lhbgtk $(shell pkg-config --libs libglade-2.0) $(shell pkg-config --libs gtk+-2.0 )

include ../../../Rules.make

