##################################
#
# Makefile para T-GTK codigo de C
#
ROOT = ../
TARGET=libcurl-hb.a

CFLAGS+=-I. -I$(ROOT)include $(shell pkg-config --cflags libcurl)

SOURCE_TYPE=c
TGTK_INSTALL=$(ROOT)lib

include $(ROOT)Rules.make
