##################################
#
# Makefile para T-GTK codigo de C
#
ROOT = ../
TARGET=libcurl-hb.a
CFLAGS+=-I. -I$(ROOT)include $(shell pkg-config --cflags libgnomedb-3.0)

SOURCE_TYPE=c
TGTK_INSTALL=$(ROOT)lib

include $(ROOT)Rules.make
