# Atención, la ruta include/lib de tdolphin tiene que estar definida, aqui o en rules.make
ROOT = ../../../

TARGET = test
SOURCES = dophin.prg

#PRGFLAGS=-I/home/rafa/repositorios/subversion/tdolphindevel/include
#LIBS=-L/home/rafa/repositorios/subversion/tdolphindevel/lib/HARBOUR/gcc/dolphin -ldolphin
#LIBS =-L./ -ldolphin 

include $(ROOT)Rules.make

