# Atención, la ruta include/lib de tdolphin tiene que estar definida, aqui o en rules.make
ROOT = ../../../

TARGET = test
SOURCES = dophin.prg

PRGFLAGS=-I$(TGTK_DIR)/tdolphin/include
LIBFILES_=-ltdolphin -lmysqlclient -lhbct
#LIBS =-L./ -ldolphin 

include $(ROOT)Rules.make

