##################################
#
# Makefile para T-GTK codigo de C
#

TARGET=libtgtk_gnomedb.a
CFLAGS+=-I. -I../include $(shell pkg-config --cflags libgnomedb-3.0)

SOURCE_TYPE=c
TGTK_INSTALL=../lib

include ../Rules.make
