# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../../
SETTINGS=$(ROOT)config/settings/minimal.mk

TARGET = demoppo
SOURCES = demoppo.prg

RESOURCE_FILE = resource.rc

#PRGFLAGS=-I$(ROOT)include
#LIBS=$(shell pkg-config --libs tgtk )

include $(ROOT)Rules.make

