/*
 * $Id: hbscript.prg,v 1.1 2010-12-27 04:16:28 riztan Exp $
 * GUI T-Gtk para Harbour
 * Uso de scripts.
 * (c)2010 Riztan Gutierrez
 * Demo en script
 */

#include "gclass.ch"
#include "tgtkext.ch"

FUNCTION MAIN( cFile, ... )


REQUEST MSG_INFO
REQUEST GTREEVIEW
REQUEST GSTATUSBAR
REQUEST GTOOLTIP
REQUEST GTOGGLEBUTTON
REQUEST GENTRY
REQUEST GSPINBUTTON
REQUEST GCHECKBOX
REQUEST GTK_CALENDAR_GET_DATE
REQUEST MSG_INFO
REQUEST MSGBOX
REQUEST GMENUBAR
REQUEST GMENU
REQUEST GMENUITEM
REQUEST GMENUTEAROFF
REQUEST GMENUSEPARATOR
REQUEST GMENUITEMCHECK
REQUEST GMENUITEMIMAGE
REQUEST XHB_LIB

 /* NetIO */
 EXTERNAL NETIO_ACCEPT
 EXTERNAL NETIO_CLOSESTREAM
 EXTERNAL NETIO_COMPRESS
 EXTERNAL NETIO_CONNECT
 EXTERNAL NETIO_DECODE
 EXTERNAL NETIO_DISCONNECT
 EXTERNAL NETIO_FUNCEXEC
 EXTERNAL NETIO_GETCONNECTION
 EXTERNAL NETIO_GETDATA
 EXTERNAL NETIO_LISTEN
 EXTERNAL NETIO_MTSERVER
 EXTERNAL NETIO_OPENDATASTREAM
 EXTERNAL NETIO_OPENITEMSTREAM
 EXTERNAL NETIO_PROCEXEC
 EXTERNAL NETIO_PROCEXECW
 EXTERNAL NETIO_PROCEXISTS
 EXTERNAL NETIO_RPC
 EXTERNAL NETIO_RPCFILTER
 EXTERNAL NETIO_SERVER
 EXTERNAL NETIO_SERVERSTOP
 EXTERNAL NETIO_SRVSENDDATA
 EXTERNAL NETIO_SRVSENDITEM
 EXTERNAL NETIO_SRVSTATUS
 EXTERNAL NETIO_VERIFYCLIENT

RUNXBS( "demoppo.xbs","1" ) 
RUNXBS( "netio_client.xbs" ) 

return nil


