/*  $Id: tgtkext.ch,v 1.1 2009-03-15 17:37:24 riztan Exp $ */
/*
 * Llamadas externas para ejecutar desde script.
 * (c)2008 Riztan Gutierrez
 */

 EXTERNAL TIPCLIENTHTTP

 EXTERNAL MSG_INFO
 EXTERNAL MSGBOX
 EXTERNAL MSG_NOYES
 EXTERNAL MSG_OKCANCEL
// EXTERNAL MSG_ALERT

// GTK Functions
 EXTERNAL GTK_WINDOW_SET_ICON
 EXTERNAL GTK_WINDOW_SET_ICON_NAME
 EXTERNAL GTK_WINDOW_SET_ICON_FROM_FILE

/*
 EXTERNAL MSGABOUT
 EXTERNAL MSGBEEP
 EXTERNAL MSGGET
 EXTERNAL MSGLOGO
 EXTERNAL MSGMETER
 EXTERNAL MSGRUN
*/

 EXTERNAL GCALENDAR
 EXTERNAL GMENU
 EXTERNAL GMENUITEM
 EXTERNAL GMENUSEPARATOR
 EXTERNAL GSTATUSBAR
 EXTERNAL GIMAGE
 EXTERNAL GMENUBAR
 EXTERNAL GMENUTEAROFF
 EXTERNAL GMENUITEMCHECK
 EXTERNAL GMENUITEMIMAGE
 EXTERNAL GTOOLTIP
 EXTERNAL GTOGGLEBUTTON
 EXTERNAL GENTRY
 EXTERNAL GSPINBUTTON
 EXTERNAL GCHECKBOX
 EXTERNAL GTREEVIEWCOLUMN
 EXTERNAL GTEXTVIEW
 EXTERNAL GSOURCEVIEW
 EXTERNAL GTOOLBAR
 EXTERNAL GTOOLBUTTON
 EXTERNAL GBUTTON

 /* native */
 EXTERNAL GTK_CONTAINER
 EXTERNAL GTK_WIDGET_SHOW_ALL


