# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../../

TARGET = test
SOURCES = odbc.prg
LIBS= -lhbodbc -mwindows

include $(ROOT)Rules.make 

