# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola
# Nota:
# Para usar este ejemplos recuerda que la libreria tgtk debe ser creada
# con soporte para Bonobo en Rules.make

ROOT = ../../../

TARGET = test
SOURCES = gda_sqlite.prg
LIBS= -lhbgda

include $(ROOT)Rules.make

