# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../
#SETTINGS=$(ROOT)config/settings/minimal.mk

export HPDF=yes

TARGET = test
SOURCES = test.prg


include $(ROOT)Rules.make

