# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

TARGET = test
SOURCES = browse.prg
#LIBS= -mwindows
#PRGFLAGS=-p
include ../../../Rules.make

