# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../../

TARGET = client
SOURCES = netio_client.prg 

include $(ROOT)Rules.make

