##################################
#
# Makefile para librerias en codigo .PRG
#

ROOT = ../../

TARGET=test
SOUCES= ejemplo.prg timprimepdf.prg tutilpdf.prg

LIBS= -lhbhpdf -llibhpdf
PRGFLAGS=-I../../include
CFLAGS+=-I../../include
TGTK_INSTALL=../../lib

include $(ROOT)Rules.make
