##################################
#
# Makefile para librerias en codigo .PRG
#

ROOT = ../../

TARGET=libgclass.a

PRGFLAGS=-I$(ROOT)include 
CFLAGS+=-I$(ROOT)include
TGTK_INSTALL=$(ROOT)lib

#CSOURCES= si tenemos ficheros C definirlos aqui

include $(ROOT)Rules.make
