##################################
#
# Makefile para librerias en codigo .PRG
#

ROOT = ../../


PRGFLAGS=-I$(ROOT)include 
CFLAGS+=-I$(ROOT)include
TGTK_INSTALL=$(ROOT)lib
TARGET=libgclass.a

#CSOURCES= si tenemos ficheros C definirlos aqui

include $(ROOT)Rules.make
