##################################
#
# Makefile para librerias en codigo .PRG
#

TARGET=libgclass.a

PRGFLAGS=-I../../include 
CFLAGS+=-I../../include
TGTK_INSTALL=../../lib

#CSOURCES= si tenemos ficheros C definirlos aqui

include ../../Rules.make
