# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../../

TARGET = pixbuf
SOURCES = pixbuf.prg
LIBS = -mwindows
include $(ROOT)Rules.make

