# Make para ejecutar segun el sistema
# -mwindows al enlazar no sale ventana consola.
# pero para depurar, va de muerte que salgan mensajes en la consola

ROOT = ../../../

TARGET = test
SOURCES  = pc-svr.prg
# Utilidades
SOURCES += util.prg
SOURCES += gpctoolbutton.prg
SOURCES += pdf.prg

SOURCES += pcedit.prg pcini.prg pcget.prg pckey.prg
SOURCES += pctapiz.prg


PRGFLAGS+=-I.

include $(ROOT)Rules.make


